name: React build and Deploy to S3

on:
  push:
    branches:
      - main # Trigger the workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}} # Specify Node.js version
          # cache: "npm" # Caches `npm` dependencies for faster builds

      # Step 2: Install Dependencies

      - run: |
          cd frontend
          ls -la  # List files to check for package-lock.json
          npm ci  # Install packages from package-lock.json

      # Step 3: Build the React Application
      - run: |
          cd frontend
          npm run build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET}} # S3 bucket name stored as secret
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS access key ID
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS secret key
          AWS_REGION: "eu-north-1" # Specify your AWS region
          SOURCE_DIR: "frontend/dist" # Directory where the built files are stored
