name: React build and Deploy to S3

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Specify Node.js version

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Caches `npm` dependencies for faster builds

    # Step 3: Install Dependencies
    - name: Install dependencies
      run: |
        cd frontend  # Go to your frontend folder
        npm ci  # Install packages from package-lock.json

    # Step 4: Build the React Application
    - name: Build the application
      run: |
        cd frontend  # Make sure you're in the frontend directory
        npm run build  # Builds the project, output to `build/`

    # Step 5: Deploy to S3
    - name: Deploy to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # S3 bucket name stored as secret
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key ID
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key
        AWS_REGION: 'eu-north-1'  # Specify your AWS region
        SOURCE_DIR: 'frontend/build'  # Directory where the built files are stored